%% fun_filterSpec()
% This function returns the valid types of input image files

function filterSpec = fun_filterSpec()
filterSpec = { ...
        '*.tif;*.tiff', 'Tagged Image File Format (*.tif, *.tiff)'; ...
        '*.bmp;*.dib', 'Windows Bitmap (*.bmp, *.dib)'; ...
        '*.gif', 'Graphics Interchange Format (*.gif)'; ...
        '*.jpg;*.jpeg;*.jpe;*.jif;*.jfif;*.jfi', 'Joint Photographic Experts Group Format (*.jpg, .jpeg)'; ...
        '*.jp2;*.jpx', 'Joint Photographic Experts Group 2000 Format (*.jp2, *.jpx)'; ...
        '*.png', 'Portable Network Graphics Format (*.png)'; ...
        '*.*', 'All Files (*.*)' };
end